#https://docs.travis-ci.com/user/reference/overview/
language: java
sudo: false
dist: trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
script:
- mvn validate 
- mvn compile 
